### ISSUE TITLE
App Stuck with "Loading..." Message

### ISSUE THREAD

**Issue by heinst** [stephen-mitchell/PebHub#4]
The app when give a proper key with all permissions cannot connect to the GitHub API, it just says "Loading..." and never does load

**Comment by stephen-mitchell** [comment]
The error you're seeing suggests that the app is having problems communicating with the GitHub API. Whilst trying to replicate this issue I discovered that requests don't seem to time out automatically, which explains why you didn't see a more helpful error message.

If you haven't already, please could you try restarting your phone and Pebble and checking that your phone has Internet access?

**Comment by heinst** [comment]
I tried that and reset the watch too, and downloaded again but didn't seem to fix it.

**Comment by heinst** [comment]
I just regenerated a new key and that seemed to work. Sorry!
